### ISSUE TITLE
Metadata not showing correctly

### ISSUE THREAD

**Issue by iamevl** [surekap/MMM-ShairportMetadata#13]
I can airplay successfully but metadata i have problems with. It was working fine until the last update. Below are my settings..

```
 {

        enabled = "yes"; // set this to yes to get Shairport Sync to solicit me$
        include_cover_art = "yes"; // set to "yes" to get Shairport Sync to sol$
        cover_art_cache_directory = ""; // artwork will be  stored in this dire$
        pipe_name = "/tmp/shairport-sync-metadata";
        pipe_timeout = 5000; // wait for this number of milliseconds for a bloc$
//      socket_address = "226.0.0.1"; // if set to a host name or IP address, U$
//      socket_port = 5555; // if socket_address is set, the port to send UDP p$
//      socket_msglength = 65000; // the maximum packet size for any UDP metada$
};
```

```
  		{
    			module: 'MMM-ShairportMetadata',
			header: "",
    			position: 'right',
    			config: {
      			metadataPipe: "/tmp/shairport-sync-metadata", // location of pipe with shairport-sync metadata
	  		alignment: "center",	// Possible values [left|right|center]. Default: center
    				}
  		},`
```
i have reinstalled shairport and even gone as far as complete reinstall of piOS (Buster) and magicmirror - made sure i "make" --with-metadata but no joy.
Read the other issue posted with similar description that was not resolved.
Have followed those instructions and also ran `tail -f /tmp/shairport-sync-metadata` and it came back with
`tail: cannot open '/tmp/shairport-sync-metadata' for reading: No such file or directory tail: no files remaining. `Because i had already reinstalled with metadata switch i figured i could create the file manually and set permissions on the file. 
I now get data when i run tail command and can now see album artwork in the module but the data does not change when i skip track - instead it continues to count up the progress time and show the first track.

it did work fine previously before the progress bar was added. 
could anyone offer suggestion on what i am missing?

Also - it would be remiss of me to not say thanks very much for the hard work that has gone into these modules!

TIA for any help offered.

**Comment by johnway94** [comment]
I also have the same problem with showing album artwork but when I change song it doesn't change and the progress bar just continues to go up. Help

**Comment by iamevl** [comment]
update:-
installed Stretch away from Buster and all is now working - possibly Buster incompatibility
