### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by ihorbond** [surekap/MMM-ShairportMetadata#2]
Installed everything per instructions and configured metadata. Music plays via shairport but nothing shows up on the mirror. Node ver 8.9.3. Current mirror version. Any ideas ?

**Comment by santiagos5** [comment]
same here.. shairport works well, but nothing shows up on mirror..

**Comment by campbell97** [comment]
Any ideas on how to debug this? Getting an error for no /tmp/shairport-sync-metadata file or directory. Assume shairport-sync has updated something but I can't even get anything to log...

**Comment by campbell97** [comment]
@ihorbond @santiagos5 You need to include `--with-metadata` in your shairport configuration, or the metadata will not be sent to the pipe. Not sure if you're still encountering the issue, but hopefully that helps.

**Comment by ScarletKnight** [comment]
Having the same issue. Can you please specify what you mean by "You need to include --with-metadata in your shairport configuration"?

**Comment by luisfalvarez** [comment]
> --with-metadata
In what part of the configuration?
